run:
  deadline: 5m
  tests: false
  # skip-dirs:
  #   - fakes # generated code
linters:
  disable:
    - golint # deprecated, use revive
    - scopelint # deprecated, use exportloopref
  enable:
    - gofmt
    - exportloopref
    - goconst
    - revive
    - prealloc
linters-settings:
  misspell:
    locale: UK