---
minimum_pre_commit_version: 2.17.0
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-imports
        args: ["-w"]
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go
        entry: make lint
        types: [go]
        language: golang
        pass_filenames: false
        require_serial: true